CREATE USER 'lp_user'@'%' IDENTIFIED BY 'lp_user' ;
GRANT ALL PRIVILEGES ON *.* TO 'lp_user'@'%' WITH GRANT OPTION;
CREATE USER 'bss_developers'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'bss_developers'@'%';
CREATE USER 'bluesage'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'bluesage'@'%';
CREATE USER 'bssadmin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'bssadmin'@'%';
CREATE USER 'ro_user'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'ro_user'@'%';
CREATE USER 'bluesage_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'bluesage_dev'@'%';
CREATE USER 'dcu_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'dcu_dev'@'%';
CREATE USER 'dcu_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'dcu_lower_admin'@'%';
CREATE USER 'hb_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'hb_lower_admin'@'%';
CREATE USER 'kind_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'kind_lower_admin'@'%';
CREATE USER 'kindretail_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'kindretail_admin'@'%';
CREATE USER 'lendage_lwr_adm'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'lendage_lwr_adm'@'%';
CREATE USER 'mfm_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'mfm_lower_admin'@'%';
CREATE USER 'mfmcorr_lwr_adm'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'mfmcorr_lwr_adm'@'%';
CREATE USER 'mig_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'mig_lower_admin'@'%';
CREATE USER 'admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';
CREATE USER 'prime_lowr_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'prime_lowr_admin'@'%';
CREATE USER 'seq_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'seq_admin'@'%';
CREATE USER 'west_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'west_lower_admin'@'%';
CREATE USER 'westerra_ro_user'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'westerra_ro_user'@'%';
CREATE USER 'hb_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'hb_dev'@'%';
CREATE USER 'hb_dev_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'hb_dev_admin'@'%';
CREATE USER 'kind_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'kind_dev'@'%';
CREATE USER 'mfm_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'mfm_dev'@'%';
CREATE USER 'mm_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'mm_lower_admin'@'%';
CREATE USER 'movement_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'movement_dev'@'%';
CREATE USER 'scu_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'scu_dev'@'%';
CREATE USER 'scu_fly'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'scu_fly'@'%';
CREATE USER 'scu_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'scu_lower_admin'@'%';
CREATE USER 'scu_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'scu_admin'@'%';
CREATE USER 'bssservicing_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'scu_admin'@'%';
CREATE USER 'activemq_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'activemq_admin'@'%';
CREATE USER 'cfcu_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'cfcu_dev'@'%';
CREATE USER 'cfcu_fly'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'cfcu_fly'@'%';
CREATE USER 'cfcu_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'cfcu_lower_admin'@'%';
CREATE USER 'cfcu_qa'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'cfcu_qa'@'%';
CREATE USER 'cfcu_uat'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'cfcu_uat'@'%';
CREATE USER 'rds_superuser_role'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'rds_superuser_role'@'%';
CREATE USER 'ro_shared_user'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'ro_shared_user'@'%';
CREATE USER 'rdsadmin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'rdsadmin'@'%';
CREATE USER 'fcm_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'fcm_dev'@'%';
CREATE USER 'fcm_fly'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'fcm_fly'@'%';
CREATE USER 'fcm_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'fcm_lower_admin'@'%';
CREATE USER 'fcm_prodmirror'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'fcm_prodmirror'@'%';
CREATE USER 'fcm_qa'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'fcm_qa'@'%';
CREATE USER 'fcm_uat'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'fcm_uat'@'%';
CREATE USER 'bluedlp_dev'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'bluedlp_dev'@'%';
CREATE USER 'bluedlp_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'bluedlp_lower_admin'@'%';
CREATE USER 'dlp_fly'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'dlp_fly'@'%';
CREATE USER 'rcu_fly'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'rcu_fly'@'%';
CREATE USER 'mbi_fly'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'mbi_fly'@'%';
CREATE USER 'servicing_lower_admin'@'%' IDENTIFIED BY 'waoij5oi34ejel';
GRANT ALL PRIVILEGES ON *.* TO 'servicing_lower_admin'@'%';

FLUSH PRIVILEGES;

SET GLOBAL log_bin_trust_function_creators = 1;
