version: "3.9"
services:
  db:
    image: ghcr.io/bluesagesolutions/mysql-5.7-bluesage:latest
    command: ['mysqld', '--sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES']
    environment:
        MYSQL_DATABASE: 'bluesage_dev'
        MYSQL_ROOT_PASSWORD: 'secret-pw'
        MYSQL_ROOT_HOST: '%'
        MYSQL_USER: 'lp_user'
        MYSQL_PASSWORD: 'lp_user'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - '~/.mysql-data-bluesage/db:/var/lib/mysql'